# Generated by Django 5.1.15 on 2026-06-25 21:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_enable_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=128, verbose_name='Название (RU)')),
                ('name_kk', models.CharField(blank=True, max_length=128, verbose_name='Название (KK)')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='Название (EN)')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Геометрия')),
            ],
            options={
                'verbose_name': 'Бассейн',
                'verbose_name_plural': 'Бассейны',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=128, verbose_name='Название (RU)')),
                ('name_kk', models.CharField(blank=True, max_length=128, verbose_name='Название (KK)')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='Название (EN)')),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='JSON-схема атрибутов')),
                ('geometry_kind', models.CharField(choices=[('point', 'Точка'), ('line', 'Линия'), ('polygon', 'Полигон')], max_length=8, verbose_name='Тип геометрии')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('kato', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='КАТО')),
                ('name_ru', models.CharField(max_length=128, verbose_name='Название (RU)')),
                ('name_kk', models.CharField(blank=True, max_length=128, verbose_name='Название (KK)')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='Название (EN)')),
                ('level', models.CharField(choices=[('region', 'Область'), ('district', 'Район'), ('okrug', 'Округ')], max_length=10, verbose_name='Уровень')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.adminunit', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Админ. единица',
                'verbose_name_plural': 'Админ. единицы (КАТО)',
                'ordering': ['kato'],
            },
        ),
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_kk', models.CharField(blank=True, max_length=200, verbose_name='Название (KK)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('kind', models.CharField(choices=[('river', 'Река'), ('stream', 'Ручей'), ('lake', 'Озеро'), ('reservoir', 'Водохранилище'), ('other', 'Другое')], default='river', max_length=12, verbose_name='Тип')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Геометрия')),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_bodies', to='catalog.basin', verbose_name='Бассейн')),
            ],
            options={
                'verbose_name': 'Водный объект',
                'verbose_name_plural': 'Водные объекты',
                'ordering': ['name_ru'],
            },
        ),
    ]
