# Generated by Django 5.1.15 on 2026-06-25 21:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_kk', models.CharField(blank=True, max_length=255, verbose_name='Название (KK)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Название (EN)')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Геометрия')),
                ('commissioning_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год ввода')),
                ('wear_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Износ, %')),
                ('ownership', models.CharField(blank=True, max_length=128, verbose_name='Форма собственности')),
                ('cadastral_number', models.CharField(blank=True, max_length=64, verbose_name='Кадастровый номер')),
                ('state_act', models.CharField(blank=True, max_length=128, verbose_name='Госакт')),
                ('responsible_org', models.CharField(blank=True, max_length=255, verbose_name='Ответственная организация')),
                ('significance', models.CharField(blank=True, choices=[('republican', 'Республиканское'), ('regional', 'Областное'), ('district', 'Районное'), ('local', 'Местное')], max_length=12, verbose_name='Значимость')),
                ('condition_status', models.CharField(blank=True, choices=[('serviceable', 'Исправное'), ('monitoring', 'Требует наблюдения'), ('repair', 'Требует ремонта'), ('emergency', 'Аварийное')], max_length=12, verbose_name='Тех. состояние (вычисляется)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'На согласовании'), ('published', 'Опубликовано'), ('decommission_requested', 'Запрошен вывод'), ('archived', 'В архиве')], default='draft', max_length=24, verbose_name='Статус жизненного цикла')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Атрибуты (по схеме типа)')),
                ('admin_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='catalog.adminunit', verbose_name='Админ. единица')),
                ('basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='catalog.basin', verbose_name='Бассейн')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_structures', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='catalog.objecttype', verbose_name='Тип')),
                ('water_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='catalog.waterbody', verbose_name='Водный объект')),
            ],
            options={
                'verbose_name': 'Сооружение',
                'verbose_name_plural': 'Сооружения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspected_at', models.DateField(verbose_name='Дата осмотра')),
                ('inspector', models.CharField(blank=True, max_length=255, verbose_name='Инспектор')),
                ('condition_observed', models.CharField(blank=True, choices=[('serviceable', 'Исправное'), ('monitoring', 'Требует наблюдения'), ('repair', 'Требует ремонта'), ('emergency', 'Аварийное')], max_length=12, verbose_name='Наблюдаемое состояние')),
                ('wear_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Износ, %')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='catalog.structure', verbose_name='Сооружение')),
            ],
            options={
                'verbose_name': 'Осмотр',
                'verbose_name_plural': 'Осмотры',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('photo', 'Фото'), ('passport', 'Паспорт'), ('act', 'Акт'), ('order', 'Приказ'), ('source_file', 'Исходный файл импорта')], max_length=16, verbose_name='Тип')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.structure', verbose_name='Сооружение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['status'], name='catalog_str_status_cda4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['condition_status'], name='catalog_str_conditi_f61947_idx'),
        ),
    ]
