# Generated by Django 5.1.15 on 2026-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_structure_inspection_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='needs_geocoding',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Требует геопривязки/проверки'),
        ),
    ]
