# Generated by Django 5.1.15 on 2026-06-26 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_structure_needs_geocoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('manual', 'Вручную')], max_length=10, verbose_name='Источник')),
                ('file', models.FileField(blank=True, null=True, upload_to='parse_jobs/%Y/%m/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обработка'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=12, verbose_name='Статус')),
                ('raw_extract', models.JSONField(blank=True, default=dict, verbose_name='Извлечённые поля')),
                ('confidence', models.JSONField(blank=True, default=dict, verbose_name='Уверенность по полям')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('match_status', models.CharField(blank=True, choices=[('existing', 'Существующий'), ('new', 'Новый'), ('needs_check', 'Требует проверки')], max_length=12, verbose_name='Статус сверки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('matched_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_parse_jobs', to='catalog.structure', verbose_name='Совпавший объект')),
                ('result_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_parse_jobs', to='catalog.structure', verbose_name='Черновик-результат')),
            ],
            options={
                'verbose_name': 'Задача парсинга',
                'verbose_name_plural': 'Задачи парсинга',
                'ordering': ['-created_at'],
            },
        ),
    ]
