# Generated by Django 5.1.15 on 2026-06-26 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('application_submitted', 'Заявка подана'), ('application_approved', 'Заявка согласована'), ('application_rejected', 'Заявка отклонена'), ('risk_alert', 'Риск-оповещение')], max_length=32, verbose_name='Тип')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('related_entity_type', models.CharField(blank=True, max_length=64, verbose_name='Тип сущности')),
                ('related_entity_id', models.CharField(blank=True, max_length=64, verbose_name='ID сущности')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx')],
            },
        ),
    ]
