# Generated by Django 5.1.15 on 2026-06-26 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_structure_inspection_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessed_at', models.DateTimeField(verbose_name='Дата оценки')),
                ('condition_status', models.CharField(choices=[('serviceable', 'Исправное'), ('monitoring', 'Требует наблюдения'), ('repair', 'Требует ремонта'), ('emergency', 'Аварийное')], max_length=12, verbose_name='Тех. состояние')),
                ('repair_status', models.CharField(choices=[('norm', 'Норма'), ('inspect', 'Требуется осмотр'), ('repair', 'Требуется ремонт'), ('critical', 'Критическое')], max_length=12, verbose_name='Статус ремонта')),
                ('next_inspection_due', models.DateField(blank=True, null=True, verbose_name='Следующий осмотр')),
                ('risk_scores', models.JSONField(blank=True, default=dict, verbose_name='Разбор/риски')),
                ('model_version', models.CharField(blank=True, max_length=32, verbose_name='Версия модели')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='catalog.structure', verbose_name='Сооружение')),
            ],
            options={
                'verbose_name': 'Оценка состояния',
                'verbose_name_plural': 'Оценки состояния',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
