# Generated by Django 5.1.15 on 2026-06-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_structure_needs_geocoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydropostReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(verbose_name='Момент')),
                ('water_level', models.FloatField(blank=True, null=True, verbose_name='Уровень')),
                ('danger_level', models.FloatField(blank=True, null=True, verbose_name='Опасный уровень')),
                ('discharge', models.FloatField(blank=True, null=True, verbose_name='Расход')),
                ('water_temp', models.FloatField(blank=True, null=True, verbose_name='Температура воды')),
                ('status_code', models.CharField(blank=True, max_length=32, verbose_name='Код состояния')),
                ('synthetic', models.BooleanField(default=False, verbose_name='Синтетическая точка')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='catalog.structure', verbose_name='Гидропост')),
            ],
            options={
                'verbose_name': 'Замер гидропоста',
                'verbose_name_plural': 'Замеры гидропостов',
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['structure', 'ts'], name='monitoring__structu_33eac4_idx')],
            },
        ),
    ]
