# Generated by Django 5.1.15 on 2026-06-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=255, verbose_name='Кто')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('entity_type', models.CharField(blank=True, max_length=64, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='ID сущности')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
