{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aquageo.fullname" . }}-db
  labels:
    {{- include "aquageo.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      name: postgres
  selector:
    {{- include "aquageo.selectorLabels" (dict "ctx" . "component" "db") | nindent 4 }}
{{- end }}
