# Generated by Django 5.1.15 on 2026-06-26 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_structure_needs_geocoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('decommission', 'Вывод из эксплуатации')], default='create', max_length=16, verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='draft', max_length=12, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Подана')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решение принято')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='catalog.structure', verbose_name='Сооружение')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
