# Generated by Django 5.1.15 on 2026-06-26 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=64, verbose_name='Номер приказа')),
                ('file', models.FileField(upload_to='orders/%Y/%m/', verbose_name='Файл приказа (PDF)')),
                ('issued_at', models.DateTimeField(verbose_name='Издан')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workflow.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Приказ о согласовании',
                'verbose_name_plural': 'Приказы о согласовании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer', models.CharField(blank=True, max_length=255, verbose_name='Подписант')),
                ('signed_at', models.DateTimeField(verbose_name='Подписано')),
                ('cert_subject', models.CharField(blank=True, max_length=512, verbose_name='Субъект сертификата')),
                ('cms_blob', models.TextField(blank=True, verbose_name='CMS (заглушка)')),
                ('valid', models.BooleanField(default=True, verbose_name='Подпись валидна')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='workflow.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Подпись (ЭЦП-заглушка)',
                'verbose_name_plural': 'Подписи (ЭЦП-заглушка)',
                'ordering': ['-created_at'],
            },
        ),
    ]
